export const GRADING_AUDIT_SERVICE = "GRADING_AUDIT_SERVICE";
export const GRADING_CONSISTENCY_SERVICE = "GRADING_CONSISTENCY_SERVICE";
export const ATTEMPT_VALIDATION_SERVICE = "ATTEMPT_VALIDATION_SERVICE";
export const FILE_CONTENT_EXTRACTION_SERVICE =
  "FILE_CONTENT_EXTRACTION_SERVICE";
